name: Continuous Integration
on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn test
